buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://download.red-gate.com/maven/release"
        }
    }
    dependencies {
        classpath "io.github.cdimascio:dotenv-java:3.2.0"
        classpath "org.flywaydb:flyway-database-postgresql:12.5.0"
    }
}


plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id "co.uzzu.dotenv.gradle" version "3.0.0"
    id "org.flywaydb.flyway" version "12.5.0"
}

group = 'com.kms'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Dotenv
    implementation 'io.github.cdimascio:dotenv-java:3.2.0'

    // Source: https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    // Source: https://mvnrepository.com/artifact/com.querydsl/querydsl-jpa
    implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'

    annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'

    // Source: https://mvnrepository.com/artifact/com.brevo/brevo
    implementation("com.brevo:brevo:1.1.6")

    // Source: https://mvnrepository.com/artifact/org.flywaydb/flyway-core
    implementation("org.flywaydb:flyway-core:12.5.0")

    // Source: https://mvnrepository.com/artifact/org.mapstruct/mapstruct-processor
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    // H2 Database for testing
    testImplementation 'com.h2database:h2'

}
import io.github.cdimascio.dotenv.Dotenv

def dotenv = Dotenv
        .configure()
        .directory(rootProject.projectDir.absolutePath)
        .ignoreIfMissing()
        .load()

def DB_HOST = dotenv.get("DB_HOST")
def DB_PORT = dotenv.get("DB_PORT")
def DB_NAME = dotenv.get("DB_NAME")
def DB_USER = dotenv.get("DB_USERNAME")
def DB_PASS = dotenv.get("DB_PASSWORD")

flyway {
    url = "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    user = DB_USER
    password = DB_PASS
    locations = ['classpath:db/migration']
    cleanDisabled = false   // enable clean
}

flywayMigrate.dependsOn classes

tasks.named('test') {
    useJUnitPlatform()
}
